project:
  type: website
website:
  title: "Placeholder for Tony Machado's Blog"
  site-url: "https://tonymachado.netlify.app/"
  google-analytics: "G-XX9ZHZC18Z"
  navbar:
    right:
      - about.qmd
      - icon: envelope
        href: mailto:tonycmachado@gmail.com
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Tony Machado. License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)."
format:
  html:
    theme: cosmo
    css: styles.css
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    toc: true
    code-link: true
comments:
  giscus:
    repo: tonycmac/blog-tony



